//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_CapDien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_noti
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public int DeviceId { get; set; }
        public string Name { get; set; }
        public string SiteName { get; set; }
        public string AdressIP { get; set; }
    }
}
