//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_CapDien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public Nullable<int> Site_Id { get; set; }
        public Nullable<int> Obser_Id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Json_query { get; set; }
    }
}
